- app/navigation/Navigator.scala
- test/navigation/NavigatorSpec.scala
Change order of trader details pages.
> CTCTRADER-108: Change navigation for journey

- conf/app.routes
URLs are inconsistent: camel case and hyphen separated. This PR changes the URLS to all be camel case until final (hyphen separated) urls are decided.
> Make all url camel case

- .g8/checkboxPage/migrations/$className__snake$.sh
- .g8/datePage/migrations/$className__snake$.sh
- .g8/intPage/migrations/$className__snake$.sh
- .g8/optionsPage/migrations/$className__snake$.sh
- .g8/questionPage/migrations/$className__snake$.sh
- .g8/stringPage/migrations/$className__snake$.sh
- .g8/yesNoPage/migrations/$className__snake$.sh
- app/utils/CheckYourAnswersHelper.scala
This is to fix the changes we have made in the generators and allow for pages to continue to be created
> Scaffolds fix

- app/computable/Derivable.scala
- app/models/UserAnswers.scala
This introduces a way to get data from UserAnswers and also use a function to derive some meaningful data from the retrieved answer using a function that processes the answer.
> Mechanism to derive information based on UserAnswers

- app/computable/Derivable.scala
- app/models/UserAnswers.scala
This introduces a way to get data from UserAnswers and also use a function to derive some meaningful data from the retrieved answer using a function that processes the answer.
> Create mechanism to derive information based on UserAnswers.

- app/forms/AuthorisedLocationFormProvider.scala
- app/forms/CustomsSubPlaceFormProvider.scala
- app/forms/IncidentInformationFormProvider.scala
- app/forms/PlaceOfNotificationFormProvider.scala
- app/forms/PresentationOfficeFormProvider.scala
- app/forms/TraderAddressFormProvider.scala
- app/forms/TraderEoriFormProvider.scala
- app/forms/TraderNameFormProvider.scala
- app/forms/events/EventCountryFormProvider.scala
- app/forms/events/EventPlaceFormProvider.scala
- app/forms/events/transhipments/ContainerNumberFormProvider.scala
- app/forms/events/transhipments/TransportIdentityFormProvider.scala
- app/forms/events/transhipments/TransportNationalityFormProvider.scala
- app/models/CustomsOffice.scala
- app/models/TraderAddress.scala
- app/models/domain/EnRouteEvent.scala
- app/models/domain/Endorsement.scala
- app/models/domain/EventDetails.scala
- app/models/domain/Trader.scala
- app/models/domain/messages/ArrivalNotification.scala
- app/services/conversion/ArrivalNotificationConversionService.scala
- test/controllers/events/transhipments/TransportNationalityControllerSpec.scala
- test/forms/events/transhipments/ContainerNumberFormProviderSpec.scala
- test/forms/events/transhipments/TransportIdentityFormProviderSpec.scala
- test/forms/events/transhipments/TransportNationalityFormProviderSpec.scala
- test/generators/DomainModelGenerators.scala
- test/generators/ModelGenerators.scala
- Change forms to consume constants
- Change model generators
- Change in tests data to fit with, in some cases, correct limits on field inputs.
> Refactor constants core to buisness domain to sit with domain models.

- app/controllers/CheckYourAnswersController.scala
- app/controllers/events/CheckEventAnswersController.scala
- app/viewModels/CheckEventAnswersViewModel.scala
- app/viewModels/Section.scala
- conf/messages.en
- conf/views/check-your-answers.njk
- conf/views/events/check-event-answers.njk
- conf/views/macros/section.njk
- test/generators/ViewModelGenerators.scala
- test/viewModels/AddContainerViewModelSpec.scala
- test/viewModels/CheckEventAnswersViewModelSpec.scala
- test/viewModels/SectionSpec.scala
Adds variants of _Check Events Answers_ for each type of transhipment
> CTCTRADERS-143 Check Event Answers

- app/navigation/Navigator.scala
- test/navigation/CheckModeNavigatorSpec.scala
> updated journey and tests to allow for checkmode to add seals

- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- project/scaffold.sbt
The project now uses Scala version 2.11.12 which comes from bootstrap-play-26 version 1.0.0
> Upgrade sbt to 1.3.6 along with plugins and libraries for compatibility

- conf/app.routes
> CTCTRADERS-281:update route

- app/assets/javascripts/ctc.js
- app/assets/stylesheets/application-ie8.scss
- conf/messages.en
- conf/views/includes/head.njk
Also
- updated Support Links copy in footer to be English
- fixed broken IE8 stylesheet link
> CTCTRADERS-314 Update autocomplete to cope with non-valid entry

- .g8/checkboxPage/conf/views/$className__decap$.njk
- .g8/datePage/conf/views/$className__decap$.njk
- .g8/intPage/conf/views/$className__decap$.njk
- .g8/optionsPage/conf/views/$className__decap$.njk
- .g8/stringPage/conf/views/$className__decap$.njk
- .g8/yesNoPage/conf/views/$className__decap$.njk
- conf/views/authorisedLocation.njk
- conf/views/customsSubPlace.njk
- conf/views/events/confirmRemoveEvent.njk
- conf/views/events/eventCountry.njk
- conf/views/events/eventPlace.njk
- conf/views/events/eventReported.njk
- conf/views/events/incidentInformation.njk
- conf/views/events/isTranshipment.njk
- conf/views/events/seals/confirmRemoveSeal.njk
- conf/views/events/seals/haveSealsChanged.njk
- conf/views/events/seals/sealIdentity.njk
- conf/views/events/transhipments/confirmRemoveContainer.njk
- conf/views/events/transhipments/containerNumber.njk
- conf/views/events/transhipments/transhipmentType.njk
- conf/views/events/transhipments/transportIdentity.njk
- conf/views/events/transhipments/transportNationality.njk
- conf/views/goodsLocation.njk
- conf/views/incidentOnRoute.njk
- conf/views/isTraderAddressPlaceOfNotification.njk
- conf/views/movementReferenceNumber.njk
- conf/views/placeOfNotification.njk
- conf/views/traderEori.njk
- conf/views/traderName.njk
headings had title listed which is incorrect
> updated scaffold to have the heading in the correct place

- app/controllers/CheckYourAnswersController.scala
- conf/views/check-your-answers.njk
Add action for the form element for check-your-answers-arrival page
> CTCTRADERS-287: A11y Tests - Bad value “” for attribute “action” on element “form”: Must be non-empty.

- app/navigation/Navigator.scala
- test/navigation/CheckModeNavigatorSpec.scala
… but not correct for consignee.
> CTCTRADERS-630: Simplified arrival: Change EORI number confirmation navigation

- app/forms/ConsigneeNameFormProvider.scala
- test/forms/ConsigneeNameFormProviderSpec.scala
this should be 35 in length as with traderName
> updated the consignee name length

- conf/messages.en
- conf/views/eoriNumber.njk
- conf/views/traderEori.njk
- Added hint text as per [Prototype Link](https://ctc-traders.herokuapp.com/arrivals/version-4/consignee-eori).
> Adding hint text as per ticket description.

- conf/views/includes/head.njk
- conf/views/includes/scripts.njk
Followed [guidance](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=149687515) in confluence
> Adding GTM

- app/connectors/ReferenceDataConnector.scala
- app/controllers/events/CheckEventAnswersController.scala
- app/controllers/events/EventCountryController.scala
- app/controllers/events/transhipments/TransportNationalityController.scala
- app/models/reference/CountryReferenceDataEndpoint.scala
- test/connectors/ReferenceDataConnectorSpec.scala
- test/controllers/events/CheckEventAnswersControllerSpec.scala
- test/controllers/events/EventCountryControllerSpec.scala
- test/controllers/events/transhipments/TransportNationalityControllerSpec.scala
Event country now pulls data from transit countries endpoint
> CTCTRADERS-1003: Normal arrival with events rejected due to incorrect country code

- app/forms/MovementReferenceNumberFormProvider.scala
- app/forms/UpdateRejectedMRNFormProvider.scala
- app/forms/mappings/Formatters.scala
- app/forms/mappings/Mappings.scala
- app/models/MovementReferenceNumber.scala
- conf/messages.en
- test/forms/MovementReferenceNumberFormProviderSpec.scala
- test/forms/mappings/MappingsSpec.scala
- test/generators/Generators.scala
> CTCTRADERS-1566: Arrivals > Movement reference number

- app/connectors/ArrivalMovementConnector.scala
- app/controllers/ArrivalRejectionController.scala
- app/controllers/TechnicalDifficultiesPage.scala
- app/models/messages/ErrorType.scala
- app/services/ArrivalRejectionService.scala
- test/controllers/ArrivalRejectionControllerSpec.scala
- test/models/messages/ErrorTypeSpec.scala
Also: 
* added more logging
* rendered technical difficulties page instead of redirecting
> [EO][CLI-23] allowed for unhandled errorTypes in the functional error block

- conf/application.conf
- Update CSP filters to handle missing security related HTTP headers
**Ticket:**
[CTCTRADERS-2918](https://jira.tools.tax.service.gov.uk/browse/CTCTRADERS-2918)
> CTCTRADERS-2918: Update CSP filters

- app/assets/stylesheets/application-ie8.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_shame.scss
> CTCP-4474 Remove ie8 support and unnecessary css
